### ISSUE TITLE
Buffer to be not defined

### ISSUE THREAD

**Issue by in-chong** [unisat-wallet/extension#102]
When I use the following method to develop the relevant plugin v3 in vite, it will cause Buffer to be not defined. I am not sure how to solve it and hope to receive relevant answers. Thank you very much
<img width="523" alt="image" src="https://github.com/unisat-wallet/extension/assets/39892972/5ec3d82a-91a1-4c26-9645-156f6726bd20">

**Comment by GGG888GGG** [comment]
@in-chong I need to forward to our dev, but they are very busy these days. Please wait.

**Comment by GGG888GGG** [comment]
This library cannot be used directly in the browser, you need to use browserify to transform the buffer.(you could refer to https://github.com/unisat-wallet/extension/blob/master/build/webpack.common.config.js ) You should make adjustments in the webpack configuration file of your Vue project.
@in-chong
