### ISSUE TITLE
I have this issue Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by crybtofool** [unisat-wallet/extension#103]
I opened my wallet today and found it on a stand by process, frozen, and the message Unexpected token '<', "<!DOCTYPE "... is not valid JSON popping up regularly. I´ve seen you had this issue in the past. Grateful for your assistance.

**Comment by crybtofool** [comment]
I uninstalled the extension and installed new and restored the wallet.
Now I get the following:
Error: html  head. title. 502 Bad Gateway / title. head. body  center  h1. 502 Bad gateway / h1  center. hr. center  nginx/1.20.1. center. body  html
I have very little knowledge on coding. The wallet was used in conjunction with a Ordinals Wallet to receive an inscription. I sent some sats to the unisat wallet and foud all this issues.

**Comment by GGG888GGG** [comment]
@crybtofool it should be fixed. Please try again. Feel free to contact us if any question.
