### ISSUE TITLE
Ord `batch inscribe send to wallet` Inscriptions not showing in unisat.

### ISSUE THREAD

**Issue by elocremarc** [unisat-wallet/extension#114]
Unisat doesnt show inscriptions using batch inscribe with ord so the inscriptions show up as normal bitcoin not bound to an inscription. 
https://mempool.space/tx/f87a6b16a1224b65f9c8ea55e1718585b3075373581689e343860c12a70d15c7

Relevent ord PRs with the changes
https://github.com/ordinals/ord/pull/2504
https://github.com/ordinals/ord/pull/2701

**Comment by elocremarc** [comment]
@huanniangstudio this is a pretty serious issue and people are going to lose inscriptions.

**Comment by hans-crypto** [comment]
I'm here for the drama! 🍿 

But seriously, people can and will lose money because of this!

**Comment by huanniangstudio** [comment]
Due to the instability of these inscriptions and frequent changes in rules, we have not been able to support unstable inscriptions yet.

Please do not use UniSat Wallet to receive cursed/unbound inscriptions.

**Comment by huanniangstudio** [comment]
However, we will continue to advance the support for cursed inscriptions, shortly after the 824544 height.

**Comment by GrizzlyChief** [comment]
> However, we will continue to advance the support for cursed inscriptions, shortly after the 824544 height.

I'm sorry, but I'm asking for clarification. Will you continue to advance the support or will you already support after the 824544 height?

**Comment by GGG888GGG** [comment]
@GrizzlyChief sorry, at present it is difficult to share details, It depends on the final implementation and results，when it is finished, we would annouce it. Tks for your attention.
