### ISSUE TITLE
Processing Inscription - Stuck  

### ISSUE THREAD

**Issue by BitcoinBRC20** [unisat-wallet/extension#115]
Hi,

I have a transaction that been processing since Aug.16th 
https://ord.link/24398668

My wallet address is: bc1q69296nydvkz8xrtmj7mcmts0zew3dc7rwgjh8q

How can I cancel this transaction to get my Trac back as it seems it got stuck in Mempool.

**Comment by BitcoinBRC20** [comment]
Any updates on this? 

My wallet address is: bc1q69296nydvkz8xrtmj7mcmts0zew3dc7rwgjh8q

**Comment by cloud6605** [comment]
Sorry for my late. I've replied to you in your latest ticket.
