### ISSUE TITLE
Should we support formatted JSON in ordinals?

### ISSUE THREAD

**Issue by oopswitch** [unisat-wallet/extension#12]
It looks that UniSat can recognize inscrible with formatted JSON, but the BRC-20 tab cannot recognize BRC20 with formatted JSON.
Is this a bug?

![screenshot](https://user-images.githubusercontent.com/128981777/236625865-8a0fb66a-3534-49dc-83c3-961f6927b4aa.png)

Thank you very much!

**Comment by cloud6605** [comment]
Do you mean the inscription doesn't list on brc-20 tab? Once the inscription is confirmed and it is valid, then it will be listed in brc-20 tab.
