### ISSUE TITLE
Unisat doesnt recognize cursed inscriptions. 

### ISSUE THREAD

**Issue by elocremarc** [unisat-wallet/extension#120]
Cursed inscriptions are not recognized by unisat and are getting spent to fees.

**Comment by hans-crypto** [comment]
WTF?! 😳

**Comment by cloud6605** [comment]
Sorry, Unisat wallet doesn't support cursed inscriptions at present, so it will be recognized as normal btc.

**Comment by GrizzlyChief** [comment]
> Sorry, Unisat wallet doesn't support cursed inscriptions at present, so it will be recognized as normal btc.

But I read in another thread that you are working on it. Or is that not true?

**Comment by GGG888GGG** [comment]
Yes, we are working on it, it could support postive number, and negative number is in plan. @GrizzlyChief
