### ISSUE TITLE
Cannot see Stamp token in my Unisat Wallet

### ISSUE THREAD

**Issue by baseer110** [unisat-wallet/extension#126]
Hello,

Yesterday I bought Stamp token from https://www.stampscan.xyz/trade. I can see transaction is complete but I cannot see STAMP token in my Unisat wallet. Can someone please help me with that?

Thanks.

**Comment by cloud6605** [comment]
I'm sorry. Unisat Wallet doesn't support stamp at present. So it didn't appear in the wallet.
