### ISSUE TITLE
Any Updates? Processing Transaction Stuck

### ISSUE THREAD

**Issue by BitcoinBRC20** [unisat-wallet/extension#127]
Hi,

I have a transaction that been processing since Aug.16th
https://ord.link/24398668

My wallet address is: bc1q69296nydvkz8xrtmj7mcmts0zew3dc7rwgjh8q

How can I cancel this transaction to get my Trac back as it seems it got stuck in Mempool.

**Comment by cloud6605** [comment]
That's transfer is already confirmed and you've sent it out.
![image](https://github.com/unisat-wallet/extension/assets/132422140/62b17d41-a268-4154-b7c6-39fd3e8d661e)

**Comment by BitcoinBRC20** [comment]
I never received my BTC, nor do I currently have my Trac. It is true I listed them, but I should either receive the payment of BTC or my Trac coins must be refunded.

**Comment by GGG888GGG** [comment]
![image](https://github.com/unisat-wallet/extension/assets/132530469/79005fe2-6077-4d96-a7b8-ba372518d6d2)
the txn already showed you got income in this trade.
