### ISSUE TITLE
两笔购买失败 但是扣款了

### ISSUE THREAD

**Issue by songyu1235** [unisat-wallet/extension#128]
早上10点，用钱包地址bc1pselngze2xe8pg4hc0dgjye5gt0xpw9rcch82yg267adfl84n20wqu230u9
购买三笔cats，显示sold，但是都没到账，晚上两笔突然显示failed ，另一笔也没到账。但是都扣款了，失败两笔越1.5万u。

**Comment by songyu1235** [comment]
用UNI几百次，第一次遇到购买失败，有点手足无措

**Comment by songyu1235** [comment]
看哈希显示成功交易
8c0cc40eb45f23f7efdbdf216d2b8044594d9c2cd04dc6470efaa4cf5d246b0e

22b03e6cc189c43302182de034e5092243a0dcbb724ac4ac3c2c04541e187b95

**Comment by cloud6605** [comment]
这两笔交易都已被内存池丢掉，所以你的付款交易也会被取消，也就是购买失败。从链上看，你的地址上也只有一笔购买成功，所以交易失败你并不会被扣款。
你可以输入你的钱包地址在mempool.space去查询核实。
