### ISSUE TITLE
谷歌浏览器的unisat钱包能不能支持比特币24位助记词的导入呢？

### ISSUE THREAD

**Issue by Valuebai** [unisat-wallet/extension#13]
我看钱包只支持12位的助记词，我的钱包是从Hiro wallet创建的，是24位的，希望你们能支持24位助记词的导入

**Comment by Sdaofazir** [comment]
赞，今天刚用unisat，觉得非常棒，太酷了

**Comment by cloud6605** [comment]
抱歉，我们目前还不支持24位助记词的导入。也许以后的版本会考虑支持。
