### ISSUE TITLE
I want to call unisat wallet api in another chrome extension

### ISSUE THREAD

**Issue by fksyuan** [unisat-wallet/extension#132]
I want to call unisat wallet api in another chrome extension, like the Metamask "https://github.com/MetaMask/extension-provider"

**Comment by cloud6605** [comment]
Then what support do you want us to give you?

**Comment by fksyuan** [comment]
Can you provide a chrome extension provider like matamask(https://github.com/MetaMask/extension-provider), or provide the code to connect the unisat extension wallet in the chrome extension?
In addition, unisat lacks chrome.runtime.onConnectExternal and chrome.runtime.onMessageExternal, so it is impossible to connect and send messages from other chrome extensiob.

**Comment by GGG888GGG** [comment]
about api, please send your api request to contact@unisat.io @fksyuan
