### ISSUE TITLE
订单扣了费用却一直显示Unconfirmed！麻烦解决一下

### ISSUE THREAD

**Issue by IAMPAUL94** [unisat-wallet/extension#133]
SAIX, transactions of bc1qs2ng2v3rt238uffnwqj4ve2qtnxgrxukjjdcn7
![微信截图_20231227213247](https://github.com/unisat-wallet/extension/assets/117254438/46a85a82-79cd-477d-ace4-d545902f68ff)

**Comment by cloud6605** [comment]
The token is minted out. Although some of your transactions is unconfirmed, but the tokens on it will be invalid. That means you got front run by others with higher gas fee.

Luckily, you got 3 valid inscriptions.
