### ISSUE TITLE
ISSUES WITH LISTING COLLECTION

### ISSUE THREAD

**Issue by rose135666** [unisat-wallet/extension#137]
![Web capture_2-1-2024_11596_github com](https://github.com/unisat-wallet/extension/assets/145853158/26458ed9-f88a-4a92-8e9a-ecd90c24355c)

i cant list my inscriptions due to these errors please can you help with the listing
 
[inscriptions.json](https://github.com/unisat-wallet/extension/files/13813502/inscriptions.json)

[meta32.json](https://github.com/unisat-wallet/extension/files/13813504/meta32.json)

**Comment by GGG888GGG** [comment]
@rose135666 please contact our official twitter https://twitter.com/unisat_wallet with .json files.
