### ISSUE TITLE
which function should we call to connet to dapp? or this just the wallet code?

### ISSUE THREAD

**Issue by Astr0-G** [unisat-wallet/extension#14]
![image](https://user-images.githubusercontent.com/57165451/236694720-c801886d-d903-4595-9e2b-e84f747ed68a.png)

I  run build:chomre:dev and get this folder, and I am wondering how to intergrate the wallet into the Dapp if you have any guides or infos coule share with me?

thank you!

**Comment by Astr0-G** [comment]
> 

Thank you so much!

**Comment by MTR1400** [comment]
Thank you very much for your time 🙏🙏🙏💯❤️
