### ISSUE TITLE
Send funds 'Back' button does not remember inputs

### ISSUE THREAD

**Issue by BTCAlchemist** [unisat-wallet/extension#140]
When I am sending funds, I click send, enter the recipient address and amount, check off RBF, click next. After I review the inputs/outputs/fee details, if I want to make changes, I click 'Back'. This takes me back to the send BTC modal, but the inputs have been cleared. This is inconvenient when editing txs and then needing to fill everything in again (amount, address, fee rate, and check off RBF). Could you make this modal remember the input details after the user hits 'Back'? Only if they click reject would the inputs get cleared.

On a different point, could you make RBF checked off by default since that gives more flexibility to users?

**Comment by GGG888GGG** [comment]
got your suggestion and forwarded to our dev, tks so much. @BTCAlchemist
