### ISSUE TITLE
Expose getBTCUtxos to websites

### ISSUE THREAD

**Issue by revofusion** [unisat-wallet/extension#141]
RIght now there is no way for developers/sites to request "safe" btc utxos from the wallet, which the wallet internally does using getBTCUtxos. This likely leads to sites transferring utxos with inscriptions by mistake. The best way to solve this would be for unisat to expose getBTCUtxos similar to getInscriptions

**Comment by GGG888GGG** [comment]
I need forward to our dev. tks for your report.
