### ISSUE TITLE
[BUG] Typeerror: Cannot read properties of null (reading atomical)

### ISSUE THREAD

**Issue by Pszz** [unisat-wallet/extension#143]
![image](https://github.com/unisat-wallet/extension/assets/12093551/f64a5c3f-db0f-4f23-9c0a-e893737d0967)

`unisat.sendInscription(address, inscriptionId, options)`

When I use sendInscription function, I get this error.
I enabled Atomics in the Unisat extension

**Comment by GGG888GGG** [comment]
@Pszz did you use v1.2.6 of unisat wallet? @Pszz

**Comment by GGG888GGG** [comment]
I suggest you open a ticket in our discord channel https://discord.com/invite/unisat , you could get reply quicker.

**Comment by tang123qi** [comment]
did U resolve it ?

**Comment by GGG888GGG** [comment]
@tang123qi it should be fixed. Please try again.

**Comment by Pszz** [comment]
> @Pszz你用的是unisat钱包v1.2.6吗？@Pszz

YES!

**UniSat Wallet 1.2.6**

**Comment by GGG888GGG** [comment]
you still got this issue?

**Comment by keene2** [comment]
same bug  when unisat.sendBitcoin

<img width="392" alt="image" src="https://github.com/unisat-wallet/extension/assets/108206051/8a5c4015-fc4f-4a4f-adea-f9d1728d042f">

**Comment by GGG888GGG** [comment]
need parseInt
