### ISSUE TITLE
Extension for Firefox corrupt

### ISSUE THREAD

**Issue by gus4rs** [unisat-wallet/extension#145]
After following the build instructions, and trying to install the xpi, Firefox throws and error

<img width="387" alt="Screenshot 2024-01-19 at 20 29 47" src="https://github.com/unisat-wallet/extension/assets/110654587/7864b969-0d63-4b42-b3cc-14da3e95cbed">

**Comment by GGG888GGG** [comment]
unisat could install on chrome and brave browser.
