### ISSUE TITLE
sendBitcoin API with multiple recipients

### ISSUE THREAD

**Issue by pokrovskyy** [unisat-wallet/extension#147]
It would be very helpful if Unisat Wallet `sendBitcoin` [API method](https://docs.unisat.io/dev/unisat-developer-service/unisat-wallet#sendbitcoin) supported multiple recipients. Any plans adding support for this?

**Comment by GGG888GGG** [comment]
Tks so much for your suggestion, I recorded it and forward to our dev. not sure if we will support it or not, we have many plans, but the time is limited.

**Comment by pokrovskyy** [comment]
@GGG888GGG would you consider accepting a PR for such functionality?

**Comment by GGG888GGG** [comment]
I forwarded your need to our dev. @pokrovskyy

**Comment by pokrovskyy** [comment]
@GGG888GGG any update on this?
