### ISSUE TITLE
I have a big problem.

### ISSUE THREAD

**Issue by mert341903** [unisat-wallet/extension#15]
"I made a trade on UniSat, but the site gave an error during the transaction. The money was deducted from my account, but the tokens in my BRC-20 wallet came in an untradable state. However, when I check the transaction records, I can never see which block it is associated with. The transactions have still not been [confirmed.]

https://unisat.io/brc20?t=1683500804129&q=bc1pjyy3pn3t0w00d8znxdnyktq7gerq5g6gmdjv82tj7nsjdkc2x2aszluphe for VMPX

https://unisat.io/brc20?t=1683504233029&q=bc1qqaeurt8ysmphk60t03vy3lh57tgl7dehvazv3t For VMPX

**Comment by geoffsmiths** [comment]
Uncomfirmed transactions may become invalid.

**Comment by cloud6605** [comment]
Sorry for my delay. Is your issue solved? I found the the VMPX token under your two addresses are OK now.
