### ISSUE TITLE
[bug]  Cannot read properties of null (reading '1')  unisat.sendBitcoin 

### ISSUE THREAD

**Issue by keene2** [unisat-wallet/extension#150]
<img width="1163" alt="image" src="https://github.com/unisat-wallet/extension/assets/108206051/fcfbaf47-99aa-4a76-839b-5e692e070521">

{
    "message": "Cannot read properties of null (reading '1')",
    "stack": "TypeError: Cannot read properties of null (reading '1')\n    at f (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1336706)\n    at tfSubError (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1337828)\n    at chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1341112\n    at Array.every (<anonymous>)\n    at t (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1341054)\n    at p (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1341606)\n    at x.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:480460)\n    at _.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:458271)\n    at f.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:384310)\n    at v.value (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:442288)"
}

**Comment by keene2** [comment]
已解决，需要 parseInt，提示一点都不清晰

**Comment by GGG888GGG** [comment]
@keene2 谢谢您的反馈，我会反馈给开发部
