### ISSUE TITLE
can not access bitcoin in an address that belongs to a unisat wallet, although i have the 12 word phrase and password!

### ISSUE THREAD

**Issue by unisatissues** [unisat-wallet/extension#152]
Other friends mentioned the problem, but I have the same problem and I cannot find a solution. I can't get past the 12 word security part. While changing the words, I changed 1 word a little and it entered the account, but the account is not my account, it is empty. please help

**Comment by GGG888GGG** [comment]
@unisatissues it is because some words you filled is not right. Please contact our discord server https://discord.com/invite/unisat and open a ticket to share us more details. We will assit you there.
