### ISSUE TITLE
 bad-txns-inputs-missingorspent

### ISSUE THREAD

**Issue by spavlovic77** [unisat-wallet/extension#154]
I started to receive this error. I restored my wallet on different PC but I still get the same error. 
Environment: Testnet

**Comment by pilootchoum** [comment]
+1

**Comment by GGG888GGG** [comment]
it was fixed. Please try again. Feel free to contact us if any question.
@pilootchoum @spavlovic77

**Comment by mintertale** [comment]
Same problem on several wallets

**Comment by magnus-beyond** [comment]
No solution to this issue yet? @GGG888GGG

**Comment by magnus-beyond** [comment]
Alright @GGG888GGG thanks for the feedback!
