### ISSUE TITLE
Unisat closed the extension window by mistake

### ISSUE THREAD

**Issue by jualy007** [unisat-wallet/extension#156]
When unisat popup a windows to wait user sign message, if user click area not on unisat window, then the unisat window will hidden, if user click unisat  extension icon again, then unisat windwos closed and reject the operation.

It would better like metamask or other wallet, if user click unisat  extension icon again, the unisat window should display and wait for user operation.

**Comment by GGG888GGG** [comment]
tks for your suggestion. I forwarded to our dev. @jualy007
