### ISSUE TITLE
Future Request: ability to switch to another independent btc address from new seed phrase

### ISSUE THREAD

**Issue by crossxx-labs** [unisat-wallet/extension#157]
Hi, unisat wallet DEVs and admin,
<br/>
    Many thanks for bringing such great btc wallet to us. I am a frequent user of the wallet. During my interaction with unisat wallet, I found it's difficult to switch from one seed phrase to another, as I have several independent seed phrases. But I found other wallets like metamask / xverse / phantom could do that with ease
<br/>
     Now I switch to another seed phrase by removing the unisat wallet extention and then reinstall and import new seed phrases. Could you bring a new feature to enable flexible of switching between seed phrases? That would greatly help users who have more than one seed phrase when using unisat wallet

Thanks in advance.

**Comment by GGG888GGG** [comment]
<img width="624" alt="image" src="https://github.com/unisat-wallet/extension/assets/132530469/7db67321-19f2-4481-af44-4160e2f27ecf">

You could restore multiple Hdwallets.

**Comment by crossxx-labs** [comment]
@GGG888GGG Thanks a lot. This really helps.
