### ISSUE TITLE
unisat.sendInscription  not allowed!!

### ISSUE THREAD

**Issue by uxuySafe** [unisat-wallet/extension#159]
![image](https://github.com/unisat-wallet/extension/assets/147620759/1a338572-7368-49b1-af6b-a95786618471)

testnet network
unisat.sendInscription("tb1p0mpvxhpg6r2v68sc3up7u6j45dczv34hmp9f7x80a93g688mk9zsp0yhuh","c10655ca0779f1c629be0f39fc8f47b2386171f96695aba1e2b026cc3fce8efdi0")

**Comment by GGG888GGG** [comment]
you could see the error details, you could not send inscriptions in batches, you need send them one by one. @uxuySafe

**Comment by uxuySafe** [comment]
> you could see the error details, you could not send inscriptions in batches, you need send them one by one. @uxuySafe

I understand, but the Wallet window.unisat method I call    https://docs.unisat.io/dev/unisat-developer-service/unisat-wallet#sendinscription

**Comment by GGG888GGG** [comment]
@uxuySafe what unisat wallet version do you use?

**Comment by keepresolve** [comment]
> @uxuySafe what unisat wallet version do you use?

![image](https://github.com/unisat-wallet/extension/assets/29271171/225a7566-70a7-4d4a-835f-8cf090ea85f4)

**Comment by GGG888GGG** [comment]
that's all for sendInscription? can you share more codes around？

unisat.sendInscription("tb1p0mpvxhpg6r2v68sc3up7u6j45dczv34hmp9f7x80a93g688mk9zsp0yhuh","c10655ca0779f1c629be0f39fc8f47b2386171f96695aba1e2b026cc3fce8efdi0")

**Comment by keepresolve** [comment]
> It is because this inscription's output value is just 294, the error prompt is not proper, please use an inscription whose output value is larger than 330 to try.

![image](https://github.com/unisat-wallet/extension/assets/29271171/1d7ad93d-e0bf-47f4-a940-64a38c8ff5e5)

**Comment by GGG888GGG** [comment]
native segwit can support 294 output value, but taproot address needs at least 330. You inscribed Transfer in native segwit address and sent to taproot address. Or you could set native segwit address as ordinal receiver address. @keepresolve
