### ISSUE TITLE
VMPX 铭刻未确认，申请退款！请UniSat官方帮忙解决！

### ISSUE THREAD

**Issue by Harlanmix** [unisat-wallet/extension#16]
https://unisat.io/brc20?t=1683514781830&q=361SXXaSdn3EAPEiPQVbYCdzbS2F2hK9jA
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/86096865/236724354-3dc4db9b-a29e-4366-9f53-6ebc587a4ce6.png">

**Comment by cloud6605** [comment]
Sorry for my delay. When the tx got into mempool, we can't refund it. Just waiting it to be confirmed, nothing can do.
