### ISSUE TITLE
 Error: bad-txns-inputs-missingorspent  Cannot fix

### ISSUE THREAD

**Issue by BootsManuva** [unisat-wallet/extension#160]
Hi I keep getting this error when I try to do any transaction on BTC testnet

I cannot send anything and I can't complete transactions from sites linked to wallet. This is happening on two wallets . both the wallet I sent tBTC to and the wallet that received it. Neither can do anything. several hours have passed 

They are both reporting strange balances:
![Screenshot 2024-03-10 210346](https://github.com/unisat-wallet/extension/assets/162927210/bc471d97-7cea-435e-b674-5a0b6c1e3660)

here you can see the 'available (safe to send)' is nearly twice the 'Balance'. The other wallet also have available larger than the balance in Unisat when I go to send

the wallets are:
tb1q0puk6v8sm8zhcteyfm707f740g99kwztn7n57k
tb1qkq9zcr9wavrzzsav5xythy32jrplh2sym8jmm0

I had thought it might fix itself after a few block confirmations but it doesn't seem to be the case 

i don't understand how this is possible :/

Any help to fix would be appreciated 

EDIT:
I was able to move all tBTC from these wallets by importing seed to Electrum and completing txns there
I then added some tBTC to one of the wallets (tb1qkq9zcr9wavrzzsav5xythy32jrplh2sym8jmm0) from a other different wallets
However, I am still not able to send from Unisat wallet still same error, thought completing txns might have cleared the issue but it has not. It is still reporting more 'Available' than 'balance' though values have changed, obviously 
seems like it must be a Unisat issue if I am able to send with another wallet app....

**Comment by GGG888GGG** [comment]
@BootsManuva Update, please try again.

**Comment by BootsManuva** [comment]
Hi,
when you say update do you mean the Unisat wallet has been updated?

It did work the next day. However same problem today. Again it works fine in Electrum so it must be a Unisat problem. Is there a fix I can implement?

**Comment by GGG888GGG** [comment]
ok, now please tell us the addresss in issue and the corresponding “safe to send” screenshot in unisat, I will forward to our dev to check. @BootsManuva

**Comment by BootsManuva** [comment]
the wallet is:
tb1qkq9zcr9wavrzzsav5xythy32jrplh2sym8jmm0

I'm using the SatoshiVM Bridge interestingly it (their bridge site) reports my available balance as: 0.10477288

Don't think the problem is with SAVM site either. I can't complete a txn on their site, but I also can't send to another wallet with the send function in Unisat

![Screenshot 2024-03-14 085826](https://github.com/unisat-wallet/extension/assets/162927210/921d1778-0246-4e2a-a272-1cb5e96e3829)

**Comment by GGG888GGG** [comment]
from your screenshot, safe to send is ok now.

**Comment by BootsManuva** [comment]
yeah I know. but cant do any kind of txn, either with site or just with 'send' in wallet

the balance and safe to send should be the same anyway - all txns from wallet on explorer have 43+ block confirmations 

still get: Error: bad-txns-inputs-missingorspent

its definitely a unisat problem, not a problem with other wallet apps

**Comment by GGG888GGG** [comment]
@BootsManuva Please try again now, and tell us if it still prompts "Error: bad-txns-inputs-missingorspent".

**Comment by BootsManuva** [comment]
Hey,

The balances never changed (safe to send never was the same as the full balance after

 I waited for over a day to see fi it would clear up after more block confirmations. It never did. I was able to fix it by using Electrum wallet and send entire balance out. And then back in after a few block confirmations.

I appreciate you coming back to me, and I hope you have managed a fix - it does seem to be a Unisat problem and I think that lots of people wouldn't manage or want to use another wallet to solve 

If the problem happens again I will revert back here and let you know

**Comment by emsit** [comment]
I have the same problem "bad-txns-inputs-missingorspent", can't do anything.

tb1p7el4rrw6c0k3fl56eh8jeyyd7qczayul9y9jwnthdrwj8dsnpjfqz6hdq9

**Comment by gigatele** [comment]
same i'm getting this as well on 2 of my wallets. can't interact with dapps/send anything. on testnet

**Comment by gigatele** [comment]
now it's 3 wallets.......

**Comment by GGG888GGG** [comment]
@gigatele it was fixed.

**Comment by magnus-beyond** [comment]
Hey @GGG888GGG what's the solution for this? You said it was fixed, but it's still happening (3 people in our team independently got this issue), how can we avoid it?

**Comment by GGG888GGG** [comment]
We know it is Testnet 3's issue, we need to restart the index again again. So when you meet this issue, you could try later. And we will upgrade to testnet 4.
