### ISSUE TITLE
助记词在哪里导出？？？？？

### ISSUE THREAD

**Issue by xinzhongyouhai** [unisat-wallet/extension#162]
助记词在哪里导出？？？？？

**Comment by GGG888GGG** [comment]
![show secret recovery phrase](https://github.com/unisat-wallet/extension/assets/132530469/3c0df2a7-8869-4146-97bc-fcf1955eec2d)
@xinzhongyouhai

**Comment by xinzhongyouhai** [comment]
> ![显示秘密恢复短语](https://private-user-images.githubusercontent.com/132530469/312035680-3c0df2a7-8869-4146-97bc-fcf1955eec2d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NzEyMTcsIm5iZiI6MTcxMzY3MDkxNywicGF0aCI6Ii8xMzI1MzA0NjkvMzEyMDM1NjgwLTNjMGRmMmE3LTg4NjktNDE0Ni05N2JjLWZjZjE5NTVlZWMyZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMVQwMzQxNTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTg3ZTAyYTcwMGU4MmExM2IxNjhkZmUwMGZkZDRkMmZhNzNlZDEwNTY5YmFjNjdjNDA1ZGMzYWI4Y2YwZmY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oI2S02KIFYjXiHKwt5LRzJlh5TYyUJBTPOZhCCZIOyc) @xinzhongyouhai

谢谢
