### ISSUE TITLE
 When adding a memo to create an OP_RETURN transaction using the latest version of the UniSat wallet, a problem occurs.

### ISSUE THREAD

**Issue by ferrarif1** [unisat-wallet/extension#167]
I want to know how to correctly create an OP_RETURN transaction using UniSat. When I add a memo in the unisat.sendBitcoin method, the data I input is treated as a string. The Rune protocol requires a format like "OP_RETURN 52 0001fe406f4001 ffdbf3de59dbf3de5912", where 52, 0001fe406f4001, and ffdbf3de59dbf3de5912 should each be parsed as separate parts, similar to the transaction example here: [mempool.space testnet transaction](https://mempool.space/testnet/tx/9edf897ad90b15b681d0c466d9e4f83c32a60fae21ee1f90313280b86a10dd89).
![image](https://github.com/unisat-wallet/extension/assets/52763111/80a64bc2-0e6f-403b-b781-51aa3cd7328b)

However, currently, when I input data like "52 0001fe406f4001 ffdbf3de59dbf3de5912", the transaction generated does not separate these data into three parts, as seen in this transaction: [mempool.space testnet transaction](https://mempool.space/testnet/tx/a200c6712e47c94bacb44871c28cc356bb189a0b4ddbfa91bd16479e37e4ce2d). Is there a way to add a method that allows users to directly add the OP_RETURN part encoded by the bscript.compile method into the transaction, for example, "6a0952554e455f544553540900a9cfd6ff1b866800"? 
![image](https://github.com/unisat-wallet/extension/assets/52763111/90c3a67c-4154-4bd8-b3e8-578672caf34c)

**Comment by GGG888GGG** [comment]
Please send your question to contact@unisat.io for developer service. @ferrarif1

**Comment by ferrarif1** [comment]
> Please send your question to [contact@unisat.io](mailto:contact@unisat.io) for developer service. @ferrarif1

ok
