### ISSUE TITLE
铸造VMPX时一次最多打24份变成了100份，好像系统有BUG，申请退款，谢谢。

### ISSUE THREAD

**Issue by KaijunFeng** [unisat-wallet/extension#17]
好像系统的BUG，铸造VMPX时一次最多打24份变成了100份，由于GAS过高导致转帐不能确认，而铭文已经打完，现申请退款，请帮忙解决处理一下，谢谢！
orderid: ca33ea5985fa56c24fdee8a4cfc96741ec3ad0b9

**Comment by cloud6605** [comment]
当当前费率低于50时，最高是允许是打100张的。高于50时，则只允许打24张。
