### ISSUE TITLE
Forget my password, then I have to uninstall the extension and then install the extention to recover from seed phrase

### ISSUE THREAD

**Issue by crossxx-labs** [unisat-wallet/extension#171]
![image](https://github.com/unisat-wallet/extension/assets/115412649/ca3b9680-ac1c-4586-a954-009e6e5c6659)

Hi, admin. 

I have forget my password, is there an entry that I can restore my wallet via seed phrase and reset my password?

Right now, I have to uninstall the unisat extension, and then reinstall, and then restore it from seed phrase.

**Comment by abangZ** [comment]
If you are sure that your mnemonic is correct,
reinstall, and then restore it from mnemonic.

if you are not sure, restore wallet in other browser to check。
