### ISSUE TITLE
After buy BTC was sended, but BRC20 not come to wallet

### ISSUE THREAD

**Issue by Maxkos941** [unisat-wallet/extension#175]
Hey, i send a tx for buy PUPS (3bccaa66f8595295bdc32070aa9795b5e7f461e431b435afdfc075de8b35562c), the transaction didn't see in mempool.space, but can look at blockchain.com, my btc was spended but tokes i buy didn't come to my wallet. Also second tx (ef45f3b5b49c027084911231cd6ed71378ce0926f107fab36fdb1655f88845fb) was the same, tx was just replace but my btc was spended from wallet, and in replace tx my wallet was not included, ask you for help to resolve this issue.

**Comment by nattaja** [comment]
![unisat](https://github.com/unisat-wallet/extension/assets/125006637/ae885ada-0802-47fb-a579-a526e0dd465b)

**Comment by nattaja** [comment]
Input Value
0.19844896 BTC
$13,352.24
Outputs
7
Output Value
0.19800592 BTC
$13,322.43

You got your money back, please check blockchain.com

**Comment by GGG888GGG** [comment]
your trade txns were cancelled actually, you could see the mempool showed "not found", mostly it is beause someone else used a higher gas fee to buy it than you. Your funds would auto go back, don't worry.

![image](https://github.com/unisat-wallet/extension/assets/132530469/f1ed8a77-326a-451f-9106-c63118a2aae4)
