### ISSUE TITLE
Stuck in loading screen when try to sign a psbt

### ISSUE THREAD

**Issue by stoXmod** [unisat-wallet/extension#178]
<img width="410" alt="image" src="https://github.com/unisat-wallet/extension/assets/60091662/0dbf299a-518d-4dbd-b997-f2cade3a63c5">

Got this in the console.
![image](https://github.com/unisat-wallet/extension/assets/60091662/af285124-cf9a-469e-8fcd-f66371e489c6)

This had been working well until this morning without any issues. Now, I can't sign for any transactions received from the backend. I didn't change anything in the codebase. I just tried this morning, and it didn't work as expected.

** PS: Signed the transaction from the backend using the WIF, worked perfectly.

**Comment by GGG888GGG** [comment]
@abangZ @huanniangstudio

**Comment by huanniangstudio** [comment]
Upgrading to the latest version of the wallet can solve this problem.
