### ISSUE TITLE
Inscription of .sats name not going through even though payment was posted and confirmed

### ISSUE THREAD

**Issue by zalupapeti** [unisat-wallet/extension#179]
Hi. I have a .sats inscription through unisat.io, connected my leather wallet, paid the fees. Transaction went through and verified on mempool and shows as valid in my wallet, but on unisat.io it says "Inscribing (waiting for confirmation)". Been almost 24 hours. I used my BTC wallet address to pay the fees and the receiving address is my ordinals wallet address. Please help. thank you.

**Comment by GGG888GGG** [comment]
could you tell us the order ID?
do you want to restart the inscribing, or refund this order?
@zalupapeti

**Comment by zalupapeti** [comment]
> could you tell us the order ID? do you want to restart the inscribing, or refund this order? @zalupapeti

hi. i reached out in your discord server and submitted a ticket. i think you guys are going to restart the transaction.

**Comment by GGG888GGG** [comment]
OK, about inscribing issue, please directly open a ticket in discord next time, we could give you a timely reply there. tks. @zalupapeti
