### ISSUE TITLE
refund application

### ISSUE THREAD

**Issue by leowasatoo** [unisat-wallet/extension#18]
inscribe failed with VMPX , repeat 24 times
 please refund, my address: bc1paj6nvz2q02ka757apnf3wlyhn858g0q0gj3x9d8d7h4qzefdpz0qp66mwu
 thx! 
 
![微信图片_20230508113352](https://user-images.githubusercontent.com/41608204/236728038-62a814f1-8f69-43ab-b343-a0b0f44c1695.png)

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by cloud6605** [comment]
Sorry, you got front run by others with higher gas fee, so your tokens are invalid. In this case, it's impossible to refund since the miners got the gas fee.
