### ISSUE TITLE
bad-txns-inputs-missingorspent

### ISSUE THREAD

**Issue by gigatele** [unisat-wallet/extension#180]
![fucked4](https://github.com/unisat-wallet/extension/assets/17942294/89c65ac6-8c13-4418-a2b8-3b8273c8e6de)
on testnet
2 wallets showing "bad-txns-inputs-missingorspent" when trying to do any kind of txn/send.

**Comment by gigatele** [comment]
3 wallets now

**Comment by gigatele** [comment]
4 wallets now

**Comment by gigatele** [comment]
5

**Comment by gigatele** [comment]
Only 2 wallets working fine now

**Comment by GGG888GGG** [comment]
sorry, the testnet server has been prone to going down recently. You could try later.

**Comment by mintertale** [comment]
How much later? I've been having the same problem since yesterday

**Comment by GGG888GGG** [comment]
you may try more times every day.

**Comment by scarlet-ibis** [comment]
having the same issue for the past two days. 

tb1p878jr8kyz2pw7268qlk3m2tpwqg7flumu5duttcrx002s0z4twkqtevt3u

> you may try more times every day.
