### ISSUE TITLE
Unisat charged me wrong fees 

### ISSUE THREAD

**Issue by usma3321** [unisat-wallet/extension#181]
Hi , I sent my btc from unisat to coinbase , it charged me 900 usd fees when it was showing way less when i sent . could someone pleaase help i sent 1.7k usd and got charged 900 usd. .Dont think this is right as unisat told me the fees would be less when sending . 

bc1q3twllxvmln69ga3nyrk0l9ypnaa7znlnpqwd23 my unisat wallet address 
https://mempool.space/tx/61ea1134d97754ccb453e6c2d0a283f3488724f5a126bba362d96d981bdc44c8 the transaction

**Comment by usma3321** [comment]
Clarification when i inscribed the fees showing was way less , when it inscribed it showed 900 usd fees. Could someone please help

**Comment by usma3321** [comment]
anyone able †o help ?

**Comment by GGG888GGG** [comment]
gas fee = fee rate * virtual size.
more inputs, more size.
also you set 1600+ fee rate.
![image](https://github.com/unisat-wallet/extension/assets/132530469/0d811f8e-7d7a-4419-9b2d-c4e4d115b0ab)
