### ISSUE TITLE
【BUG】get no utxo

### ISSUE THREAD

**Issue by AmAzing129** [unisat-wallet/extension#185]
https://wallet-api.unisat.io/v5/address/btc-utxo?address=

After minting runes, even I have utxos, it still return [], which causes all my bitcoin  unavailable.

**Comment by GGG888GGG** [comment]
@huanniangstudio @abangZ

**Comment by AmAzing129** [comment]
<img width="1210" alt="image" src="https://github.com/unisat-wallet/extension/assets/115673583/e6616fe6-a78d-4f02-bc53-0de83e35b47a">
I see why this happens. Becasue runes balance is awlays unavailable. You should exclude that when counting 500.

**Comment by GGG888GGG** [comment]
Yes, we known this issue, will fix it in 1.3.2 @AmAzing129

**Comment by GGG888GGG** [comment]
1.3.2 is released. @AmAzing129
