### ISSUE TITLE
Unconfirmation

### ISSUE THREAD

**Issue by gdhnifchxh** [unisat-wallet/extension#192]
i face a problem which showing unconfirmation
![Screenshot_2024-05-05-16-31-09-73_3cb2fbc00dfeeb25f657942671f65b5b](https://github.com/unisat-wallet/extension/assets/168968315/5921f8c0-2cdb-45e5-9e02-d4104e408e47)

**Comment by GGG888GGG** [comment]
Generally it means your fee rate is lower than the current mempool fee rate.
Please check the fee rate in mempool first: https://mempool.space/ , and fill in your address to check your txns' status.
