### ISSUE TITLE
My entire BTC balance is unavailable

### ISSUE THREAD

**Issue by Zorba131** [unisat-wallet/extension#195]
I sent some BTC from the OKX exchange to the Native Segwit wallet address of UniSat. The transaction has multiple confirmations, but my entire balance is unavailable. I see two dozen inscriptions in the “Ordinals - All” tab. How can I make my entire balance available without making mistakes?

**Comment by GGG888GGG** [comment]
maybe you received btc tied with inscriptions, please check Ordinals, and see if any inscription is larger than 10K sats, if yes, click it ->Split, to split the normal btc and inscription. @Zorba131

**Comment by Zorba131** [comment]
> maybe you received btc tied with inscriptions, please check Ordinals, and see if any inscription is larger than 10K sats, if yes, click it ->Split, to split the normal btc and inscription. @Zorba131

Is there no risk in this action?
Is there an additional fee required?
Do I need to select custom OutputValue?
Will this action need to be done with all 20 inscriptions?

**Comment by GGG888GGG** [comment]
no risk if they are just general ordinals that we could support.
yes, it need to on chain, it needs gas fee, more outputs more gas fee, you could check network in Sign page.
just use the default seeting.
you could click one which has largest sats to split first, after finish, then re-check All->Ordinals. because many inscription boxes may be a merged one. @Zorba131

**Comment by Zorba131** [comment]
> no risk if they are just general ordinals that we could support. yes, it need to on chain, it needs gas fee, more outputs more gas fee, you could check network in Sign page. just use the default seeting. you could click one which has largest sats to split first, after finish, then re-check All->Ordinals. because many inscription boxes may be a merged one. @Zorba131

Thank you, I have splitted the inscriptions and gained access to almost the entire amount of BTC, but there are still 20 ordinals left with a small amount of BTC that can only be “sent”. How to convert them to BTC?

**Comment by GGG888GGG** [comment]
generally they are 330, 546 sats inscriptions. It is not cost-effective to spend these small utxos, because more inputs more gas fee in txn .
Income does not cover expenses.
