### ISSUE TITLE
Unable to obtain txid on this API, may I ask what's going on. Test network

### ISSUE THREAD

**Issue by fyfy2023** [unisat-wallet/extension#197]
try {
  let {txid} = await window.unisat.sendInscription("tb1q8h8s4zd9y0lkrx334aqnj4ykqs220ss7mjxzny","e9b86a063d78cc8a1ed17d291703bcc95bcd521e087ab0c7f1621c9c607def1ai0",{feeRate:15});
  console.log("send Inscription 204 to tb1q8h8s4zd9y0lkrx334aqnj4ykqs220ss7mjxzny",{txid})
} catch (e) {
  console.log(e);
}

Unable to obtain txid on this API, may I ask what's going on. Test network ????

**Comment by GGG888GGG** [comment]
let {txid}  -->  let txid @fyfy2023

**Comment by KnucklesTheRunner** [comment]
```
try {
    let address = "tb1q8h8s4zd9y0lkrx334aqnj4ykqs220ss7mjxzny";
    let inscriptionData = "e9b86a063d78cc8a1ed17d291703bcc95bcd521e087ab0c7f1621c9c607def1ai0";
    let options = { feeRate: 15 };

    let { txid } = await window.unisat.sendInscription(address, inscriptionData, options);
    console.log("Inscription sent to", address, "TXID:", txid);
} catch (e) {
    console.error("Error sending inscription:", e.message);
    console.error(e);  // To log the full error object and inspect other properties
}
```


Can you please try it?

**Comment by GGG888GGG** [comment]
let { txid } = 
should be 
let txid =
@KnucklesTheRunner
