### ISSUE TITLE
support for regtest. 

### ISSUE THREAD

**Issue by kodomo-kazuko** [unisat-wallet/extension#198]
The bitcoin faucet's are running dry so could it be possible for unisat to support regtest in the future?

**Comment by GGG888GGG** [comment]
we are working on openng a new testnet.

**Comment by jimtracy1007** [comment]
> we are working on developing a new testnet.

Is there a specific time, because the existing test network is very difficult to use?

**Comment by GGG888GGG** [comment]
sorry, not sure the exact time, maybe a month.
