### ISSUE TITLE
钱包转出未到账

### ISSUE THREAD

**Issue by qio0617** [unisat-wallet/extension#202]
![image](https://github.com/unisat-wallet/extension/assets/172481607/f94c417b-4dd7-4ee7-9546-731d1be302b0)
![image](https://github.com/unisat-wallet/extension/assets/172481607/8f8cd43a-0d35-4d65-990d-e5449fd09582)

**Comment by GGG888GGG** [comment]
从截图你可以看到 两笔交易都在链上未确认 因为你的费率比内存池目前的费率低 你需要等待或者用加速工具加速 @qio0617
