### ISSUE TITLE
$VMPX casting failed, a total of 40 times, BTC was deducted, please help the official to return it, thank you!

### ISSUE THREAD

**Issue by qq877204568** [unisat-wallet/extension#21]
unisat wallet address: bc1ptcwk7jpyfmmum2j9vtngxz76d8laq244hdwhpqgn9qrtu27ejw0q7wwpnw

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by cloud6605** [comment]
Sorry, you got front run by others with higher gas fee. When you txs are confirmed, the token is out of supply, so your tokens are invalid. And unfortunately, there's no refund, the miners got the gas fee.
