### ISSUE TITLE
Error:bad-txns-inputs-missingorspent

### ISSUE THREAD

**Issue by anonymous4me** [unisat-wallet/extension#214]
I have 9 acounts，but now 5 have the same error
Error:bad-txns-inputs-missingorspent
can not made any tx
please help me ,thank you

**Comment by anonymous4me** [comment]
![image](https://github.com/user-attachments/assets/27aada25-61b2-4f39-8383-6b3b0e9c6128)

**Comment by anonymous4me** [comment]
![image](https://github.com/user-attachments/assets/5cc70d9c-e9d6-4b64-859f-f7ef3f49365d)

**Comment by anonymous4me** [comment]
On testnet,my wallet addr:
tb1qq4tt2y4ds2eex4dpevht9k3y26e3s58uzvyc7r
tb1qugx6um42d5xrksfr8pf9m7wydzj69596ux0kpm
tb1q29zefqklrzlxzulel7zsd0flpd3re3mxm8cpfh
tb1qrr6xmjmyp36wf4tr9kjtz3pc26x6n6sfy3p4jh

**Comment by GGG888GGG** [comment]
sorry, it is testnet indexer issue, it needs time to re-run. Please wait for some time, I will notify you when fixed. @anonymous4me

**Comment by anonymous4me** [comment]
> sorry, it is testnet indexer issue, it needs time to re-run. Please wait for some time, I will notify you when fixed. @anonymous4me

thank you bro,ok,I will wait

**Comment by GGG888GGG** [comment]
@anonymous4me now you could try again.

**Comment by anonymous4me** [comment]
> @anonymous4me now you could try again.

Thank you very much,Has returned to normal
