### ISSUE TITLE
Connect to Unisat

### ISSUE THREAD

**Issue by MekGha** [unisat-wallet/extension#219]
I can't connect my Unisat wallet in Fractal and i don't see the bouton Connect To BTC Wallet

**Comment by GGG888GGG** [comment]
PLease upgrade to v1.4.5(follow below to switch the right chain) and try again. If you still have any question, please open a ticket in our discord.
![image](https://github.com/user-attachments/assets/f4a6ec29-49b0-473d-a0e0-60c73780d83e)
