### ISSUE TITLE
I cannot log into unisat wallet with my seed phrase

### ISSUE THREAD

**Issue by icecreamed852** [unisat-wallet/extension#220]
Help - I am unable to log into my unisat wallet. On 'step 2' after entering my seed phrase I am unable to press 'continue'. What can I do? I've tried uninstalling and reinstalling the extension already. I am using Google Chrome the browser version is also up to date.

**Comment by GGG888GGG** [comment]
There are some wrong in the filled words. Please carefully check again.
in addition, you could check the words' correctless here https://raw.githubusercontent.com/bitpay/bitcore-mnemonic/master/lib/words/english.js
