### ISSUE TITLE
Regarding the  popup wallet extension to connect wallet

### ISSUE THREAD

**Issue by Ce1ling** [unisat-wallet/extension#225]
When the website is not connected to the wallet, calling some methods will automatically pop up the wallet extension's connected wallet. such as `getVersion`, `getBalance`, `getPublicKey` etc. 

Is this behavior supposed to happen? 

I saw this paragraph in the official documentation:  "You should only initiate a connection request in response to direct user action, such as clicking a button. You should always disable the "connect" button while the connection request is pending. You should never initiate a connection request on page load."

I very much agree with this statement, but the API doesn't seem to do this well. this will cause developers to have greater troubles.

Can you explain the reason, please?

Thanks for your reply.

**Comment by Ce1ling** [comment]
I think we should only pop the wallet connection via `requestAccounts`.

**Comment by cloud6605** [comment]
That paragraph means connecting wallet should be done by user. Not by app.
After user connected to wallet, then you can call those functions. @Ce1ling

**Comment by Ce1ling** [comment]
Anyway, thank you for your reply. If this is not considered a bug and will not be fixed, then we can close this issue. @cloud6605

**Comment by cloud6605** [comment]
Yes, those function will cause the wallet to pop up. So we suggest you don't call those functions if the user doesn't connect  to wallet.  Doing so may avoid this kind of issues. @Ce1ling

**Comment by Ce1ling** [comment]
Okay, I got it. 

Thanks.
