### ISSUE TITLE
The following error occurs when purchasing FB  domain name with Unisat.io: Payment Failed

### ISSUE THREAD

**Issue by bemvp** [unisat-wallet/extension#228]
![1726475438867](https://github.com/user-attachments/assets/24339e30-c2b1-472b-b589-5b8126319a5a)
![1726475483312](https://github.com/user-attachments/assets/9ec2072c-f0a7-40ba-947f-c41bb3fd77ea)
![1726475629598](https://github.com/user-attachments/assets/fd565563-d99b-495c-a1d3-6967e97b2cbd)
The following error occurs when purchasing a domain name with Unisat.io:
Payment Failed

**Comment by GGG888GGG** [comment]
@bemvp Please wait with patience.
too-long-mempool-chain means your address has reached the 24 unconfirmed times limitation on btc chain, you could not operate the funds in the address at present, you need to wait for some pending txns being confirmed, then your address can be unlocked.
