### ISSUE TITLE
Token Deployed and Mint but forgot to put received address.

### ISSUE THREAD

**Issue by grullan** [unisat-wallet/extension#24]
Is there a way to have a token I  created on unisat sent to me? I created one and I didn't put my receive address and it went to unisat's generic address I suppose. Any help would be great. I can provide any information as needed.

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by cloud6605** [comment]
Once you connect your wallet to unisat.io, the receiver address will be auto-filled. Can't you see your tokens under your address? Please tell me the order id, then i'll check it for you.
