### ISSUE TITLE
VMPX engraves that there is no proxy payment, BTC is transferred to the team account, and a refund is applied for! Please UniSat official help to solve

### ISSUE THREAD

**Issue by feimao1** [unisat-wallet/extension#28]
TX1:49152af9a18f443b783ccb14c8610aee5e540899d75c7bb363335605ea759aff
TX2:09cc0e0f5ec97f14d64280ed7e348ee28d40f7897182a3dd3f3ef03cdd861efd

![微信图片_20230510050203](https://github.com/unisat-wallet/extension/assets/84235449/aab003b4-70b6-4f3a-9d13-3a5dd1d82f23)

orderId:a12c77f1e2dbdfea5547c59b3a20d82d655dd179
orderId:4e3369842cfdffb7853e4e33f6e1994dbf8c844e

I paid two bills, but I checked TX, btc was still not inscribed on the receiving address, and I didn’t receive vmpx myself. I request a refund. Thank you.

The return address is: bc1pyd8nvmk8dx4thnnaz6cnng2zmk4rdy7htm8d0w0zkhdq9wsr23rqzrd7vh

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by cloud6605** [comment]
Sorry for my deplay.
The two orders are already refunded.
