### ISSUE TITLE
充了0.31，花了0.1，链上显示还有0.21BTC，钱包Balance显示0.21，Available却没有了

### ISSUE THREAD

**Issue by renyuzh** [unisat-wallet/extension#29]
https://mempool.space/zh/address/bc1pz9y8nspgwmz47zt78x0y667sxdga2dg8nhsya8p2hq4eeukf8xzs3du93d
<img width="344" alt="image" src="https://github.com/unisat-wallet/extension/assets/8084980/cc687ccf-6e38-4290-a0c6-a1f6e1ba4c87">

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by BestSoftwareenginee** [comment]
同樣的事情發生在我身上，但感謝 Blackhathacker111 幫助我收回了我所有的資金，通過電報給他發消息，他的電報用戶名是 https://t.me/Blackhathacker111

**Comment by truongnghia** [comment]
Tôi  sẽ nhận được điều gì.  Mình biết tiếng Việt

Vào 21:20, T.4, 31 Th5, 2023 BestSoftwareenginee ***@***.***>
đã viết:

**Comment by cloud6605** [comment]
Usually because there's unconfirmed tx in your balance.

**Comment by truongnghia** [comment]
số dư của tôi

**Comment by cloud6605** [comment]
Sorry, what's your issue? If you have any issue when using unisat wallet, please describe it in detail, then we'll help you as soon as possible.
