### ISSUE TITLE
UNCONFIRMED

### ISSUE THREAD

**Issue by suoyaya** [unisat-wallet/extension#30]
![image](https://github.com/unisat-wallet/extension/assets/84717886/ffd8c182-f527-4519-8d6c-768a6c0ddc1d)

Can I apply for a refund, see details

https://blockstream.info/address/bc1p6np7u3dlj84t63h5ykg3xllghg23tm6p3g4achp4lek9242e5rnqqzjezf

**Comment by BestSoftwareenginee** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111
