### ISSUE TITLE
Is there recovery vault for my seed phrase like MM ? 

### ISSUE THREAD

**Issue by 0xLxcas** [unisat-wallet/extension#31]
My extension crashed and i don't saved my seed phrase. So i have some BTCs lost on my wallet that i can't log in. So is there a solution for me ? I think about this article from metamask support : https://support.metamask.io/hc/en-us/articles/360018766351 

Have a nice day all !

**Comment by He199402** [comment]
I also encountered the same situation, if there is a good recovery method, please let me know, thank you

**Comment by geoffsmiths** [comment]
Always store your seed phrase! Otherwise you get out of luck.

Tips and use it on your own risk:

If the extension crashed but you know your password try open Chrome in safe mode (https://nordvpn.com/nl/blog/chrome-safe-mode/) and try to login again. 

Wat also could help is to open the extension in expanded view of unisat wallet. In my case this url looks like this:
chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/index.html#/main . Try pasting it inside the google chrome address field and hit enter.

These are the tips that I could think of. 

Good luck [0xLxcas](https://github.com/0xLxcas)

**Comment by 0xLxcas** [comment]
Hi, thanks for your answer ! My problem is that I created another wallet on
the old one. If I try your tips my new wallet is logged in :(

Le ven. 12 mai 2023 à 21:04, Jeffrey Schmitz ***@***.***> a
écrit :

**Comment by geoffsmiths** [comment]
Then I'm afraid there's nothing much you could do. I'm sorry for losing BTC this way.

**Comment by 0xLxcas** [comment]
I’m looking for local file with my private key inside (like metamask :
https://www.reddit.com/r/Metamask/comments/lrcvkz/for_anyone_who_has_ever_lost_their_seedphrase/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button
)

But my old wallet files are damaged and there is less documentation for
Unisat wallet than metamask.

Le ven. 12 mai 2023 à 21:31, Jeffrey Schmitz ***@***.***> a
écrit :

**Comment by BestSoftwareenginee** [comment]
> My extension crashed and i don't saved my seed phrase. So i have some BTCs lost on my wallet that i can't log in. So is there a solution for me ? I think about this article from metamask support : https://support.metamask.io/hc/en-us/articles/360018766351
> 
> Have a nice day all !

Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by BestSoftwareenginee** [comment]
> I also encountered the same situation, if there is a good recovery method, please let me know, thank you

Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by geoffsmiths** [comment]
> 

Please do not fall for this comment, if the person has a solution the person should be helpful enough to place the solution here. Do not enter his telegram.

**Comment by BestSoftwareenginee** [comment]
> Please do not fall for this comment, if the person has a solution the person should be helpful enough to place the solution here. Do not enter his telegram.

Don’t say what you don’t know I’m not the one who knows how to do it he has helped a lot and helped me too let me try their luck than thinking everyone here is a liar

**Comment by geoffsmiths** [comment]
I'm only saying that the solution should be shared here so that everyone who encountered the same issue could solve theirs as well here. Also, I haven't said that everyone is a liar.
