### ISSUE TITLE
Paid and returned to pending

### ISSUE THREAD

**Issue by facebig6** [unisat-wallet/extension#32]
Hi! My order has been paid and displayed in queue at the time, but returned to the pending status after a while, can I receive a refund? Thank you!

OrderId: 2037a46c054d0baf0bbe3d192ecea43a0c704176

Wallet address: bc1pfrldxunx53tsz9svw4w36f5kk3ycrjs26hwpemjnrc0002vj74ss7thfht

**Comment by cloud6605** [comment]
Sorry for my delay. The order is already refunded.
