### ISSUE TITLE
几笔订单未付款，可以帮忙取消吗

### ISSUE THREAD

**Issue by wokakaf** [unisat-wallet/extension#37]
order id are as follows:
0ee9353abebe4f10f299d39fc336febfc0a5c3a3
c92c082594e41dd3aaeeefc5725633522a20a551
a6e0d67b5d57edb1f232864eb181c46c8c1e2f82
aed1d411e1b36027dd57c1ae8a57dc5e010b01f4
c548ac5ebae676512124f31c29a770911a59b8e1
2cd9b9a3894a114c371eeb819f6999023c75fb86
97a2ab981def9dfb2218d4d67bc50f56d829a50e

**Comment by cloud6605** [comment]
Sorry for my delay. Order 97a2ab981def9dfb2218d4d67bc50f56d829a50e was refunded on May 15th. txid: 1040cc1354e086d033c5edf416287251c78f501b4b111528c8864f1e73e6328f
And other orders are not paid yet.
