### ISSUE TITLE
mint bdou订单未成功，nft也没有铭刻。钱已付，申请退款

### ISSUE THREAD

**Issue by wuxinguocuo** [unisat-wallet/extension#38]
https://blockstream.info/address/bc1qdlc8feuma0yg0uwn3zf82jgmxzd3las5lkurrf

**Comment by cloud6605** [comment]
Sorry for my delay. Your order is completed. But you got front run by others. when your tx is confirmed, the token is out of supply, so the tokens you got is invalid.
![image](https://github.com/unisat-wallet/extension/assets/132422140/5ccd6e87-1222-4524-a6ff-71b49b002300)
