### ISSUE TITLE
Not able to list BRC20 NOOT token => Error: get nft detail failed

### ISSUE THREAD

**Issue by vineetpant** [unisat-wallet/extension#39]
I listed NOOT token and unlisted it, Now i am trying to list it again but getting following error .

 Error: get nft detail failed
 
 I tried to transfer it to exchange address but same error is displayed, I have inscribed transfer but it doesn't let me transfer or list , i am just stuck on this error.

My available balance for NOOT shows 0 and all tokens showing transferable.

**Comment by cloud6605** [comment]
Have you figure out your issue?
If not, give me your wallet address, I'll check it.
