### ISSUE TITLE
提现后余额不正确

### ISSUE THREAD

**Issue by xinming365** [unisat-wallet/extension#41]
链上交易记录在这里，https://blockchair.com/bitcoin/transaction/e90760c027a4f71af92beb60173a0eaaaa6e055f998cbf90b456d038a5f777ad
usdt到了这个地址后，钱包无法显示，再没法使用了

**Comment by cloud6605** [comment]
是unisat钱包么？你的地址是什么？这个提现的手续费相当高呀，比你收到的钱还多。
![image](https://github.com/unisat-wallet/extension/assets/132422140/5dc6b94e-a385-44b7-a4ed-ee34ddc18bf7)

**Comment by cloud6605** [comment]
你好，你的问题解决了么？

**Comment by xinming365** [comment]
没有解决，不同网络的原因。请问你是unisat钱包官方的客服么，可以帮我解诀一下吗

在 2023年6月27日，15:12，cloud6605 ***@***.***> 写道：

﻿

你好，你的问题解决了么？

**Comment by cloud6605** [comment]
是的，我是官方客服。钱包无法显示是什么意思？你的地址是什么？

**Comment by cloud6605** [comment]
UniSat钱包不支持USDT，所以不会显示。你可以把UniSat钱包的种子导入小狐狸或其他支持USDT的钱包，然后转走就可以了。

**Comment by GGG888GGG** [comment]
@xinming365

**Comment by xinming365** [comment]
我试了，余额无法正确显示的。私钥导入-ethereum 网络-usdt代币，依然是0的余额

**Comment by cloud6605** [comment]
再次查看了你的交易，你是从gateio 提现到MjZi地址，对么？
![image](https://github.com/unisat-wallet/extension/assets/132422140/d6828f26-53ec-496f-ae5b-b582b0a71669)
从图上来看，你的钱包只是到了0.00000546 BTC而已，并不是USDT代币，也不是铭文。

**Comment by GGG888GGG** [comment]
@xinming365

**Comment by xinming365** [comment]
对的，你在查看一下，有一个因为网络消失的960usdt，并没有到MjZi地址

在 2023年7月10日，13:31，cloud6605 ***@***.***> 写道：

﻿

再次查看了你的交易，你是从gateio 提现到MjZi地址，对么？
[image]<https://user-images.githubusercontent.com/132422140/252235722-d6828f26-53ec-496f-ae5b-b582b0a71669.png>
从图上来看，你的钱包只是到了0.00000546 BTC而已，并不是USDT代币，也不是铭文。

**Comment by GGG888GGG** [comment]
链上如果没有话，就表示这笔交易根本没有发生，要跟交易所沟通看什么问题。 @xinming365

**Comment by GGG888GGG** [comment]
经过程序员分析，推测转到了一个比特币二层区了，叫Omini      @@@@@Layer的二层协议，因为不是Oridnals协议，所以我们也不支持这个协议，你安装OminiLayer的比特币钱包应该就可以看到了，研究下OminiLayer二层协议应该有办法把钱转换成btc。
https://omniexplorer.info/search/3GL1yd2n9xT9qqdmbqocPWt5MJBfv7MjZi

**Comment by GGG888GGG** [comment]
@xinming365
