### ISSUE TITLE
Market desposits BRC-20 inscriptions in payment address instead of inscription address

### ISSUE THREAD

**Issue by natureisbestNFT** [unisat-wallet/extension#42]
xverse wallet makes very clear taproot is for inscriptions and nested segwit for money (it doesn't support native segwit). And when you connect sites to xverse it says "address request" from the site, and gives a payment address *and* an address for receiving ordinals.

But unisat market was refusing to work unless unisat wallet was set to an address type with enough money in. But when it was set to native taproot (which had money), it deposited the BRC-20 transfer inscription there, without warning. Now I don't know if I can do *anything*, for risk of spending inscribed sats.

**Comment by abc0xmattyic333** [comment]
Had the same issue. 🤦🏼‍♂️

**Comment by cloud6605** [comment]
Every type of wallet address in unisat can both hold ordinals and btc. the inscriptions will sent to the address which you connected.

**Comment by natureisbestNFT** [comment]
> the inscriptions will sent to the address which you connected.
Yes, that's the problem. It should either warn when it connects, or warn when setting up the trade, or allow connecting 2 address types, like Magic Eden. Now the money is in the ordinals address, and although each address can support both money and ordinals, I don't know what software can send the money without accidentally sending ordinals, and how reliably, and whether the latest version of such software has introduced a bug, so they money is stuck and effectively lost. Even if a wallet is reliable on this, a site it's connected to may propose a transaction to sign, to send money, and that site may have failed to make the transaction ordinals aware.

So it's reasonable that some people want to keep money and ordinals separate, and that should be respected. It would be very easy to give a warning one time when connecting the wallet, if unisat insists on connecting only a single wallet address.

**Comment by cloud6605** [comment]
Thanks for your suggestion. I've written down your advice, maybe we'll consider adding this warn in future version.

**Comment by cloud6605** [comment]
BTW, when inscribing, you can input another address as receiver address.
