### ISSUE TITLE
订单不成立但钱包被扣款

### ISSUE THREAD

**Issue by facebig6** [unisat-wallet/extension#44]
订单：8a4ed4c9ed06c71426e290276369175ca8d94445
当时打core付款阶段卡住了，图标一直在转，刷新后回到pending状态，但钱包已经被扣款，请退款。
钱包地址：bc1pfrldxunx53tsz9svw4w36f5kk3ycrjs26hwpemjnrc0002vj74ss7thfht

**Comment by cloud6605** [comment]
你的订单已在5月14日退款。
txid: 2abcad62f9dcde7f75cfef67b7930b24b1d0bde6166e237865413f52ac9a261f
