### ISSUE TITLE
付款过程页面出错，订单未成立，钱包已扣款，请退款

### ISSUE THREAD

**Issue by facebig6** [unisat-wallet/extension#48]
订单：5bd2f5d9bdc2a85b4cac392597659f244c4048bb
钱包：bc1pfrldxunx53tsz9svw4w36f5kk3ycrjs26hwpemjnrc0002vj74ss7thfht
![QQ截图20230515231159](https://github.com/unisat-wallet/extension/assets/132813750/28668e54-10d9-4815-a9b5-63551ca814d2)

**Comment by cloud6605** [comment]
The refund is done. txid: 64a43af9007c9be8f1d5a93215208e1c04c3cdd4320302c75d34126d6a0d607e
please check your address bc1pfrldxunx53tsz9svw4w36f5kk3ycrjs26hwpemjnrc0002vj74ss7thfht

**Comment by MTR1400** [comment]
Thank you very much 🙏🎉 my dear
