### ISSUE TITLE
Anyway to sign rawTX prior to pushTX?

### ISSUE THREAD

**Issue by msmalley** [unisat-wallet/extension#49]
I see that there is support for pushing raw TXs (as opposed to PSBTs) - but I cannot find any documentation regarding how to get unisat to sign rawTXs prior to pushing them - or is this part of the push process?

Does anyone know if it is possible to get unisat to sign rawTXs (not PSBTs)?

**Comment by adityanithariya** [comment]
Do you know how to sign using PSBTs?
Please let me know.
