### ISSUE TITLE
Feature Request: 24 Word Seed Phrase

### ISSUE THREAD

**Issue by jzgdev** [unisat-wallet/extension#5]
Is there any plan to implement being able to import 24 word seed phrases?

**Comment by kyranjamie** [comment]
+1 this would allow better interoperability between wallets

**Comment by ShadXo** [comment]
I don't understand why wallets don't support 24 word mnemonics. I would like this feature too.

**Comment by joshavenue** [comment]
+1 Agreed with this.

**Comment by PicklErik21** [comment]
Agreed to this as well, especially since a lot of beginners started with ordinals using sparrow and the 24 word seed phrase.

**Comment by cloud6605** [comment]
Thanks for the suggestion. I've written it down. Maybe we'll consider this feature in the future version.
