### ISSUE TITLE
BRC network shows to account, does show failure on unisat

### ISSUE THREAD

**Issue by zxl886** [unisat-wallet/extension#50]
I in the BRC network mint (bc1q0lvtavy8g2pqlrvmn4jmjea5z5ak3pv68npdsw) show to account, In unisat display failure Hash value (476 ea8707649dbc584398f58cfd20139d0b083a9fe140fa70aca2cfa6563074b)

**Comment by cloud6605** [comment]
That's because you got front run by others with higher gas fee rate. When your tx was confirmed, the token you were minting was already out of supply, so your tokens were invalid, and they didn't display in your wallet.
