### ISSUE TITLE
帮帮大学生，吃不上饭了，冲到交易所半天都没有确认

### ISSUE THREAD

**Issue by Y12310** [unisat-wallet/extension#51]
我在5.16上午提币出去，现在还没有到账，bc1pnyvll0yrz5fq2ys4urxqsyucfchqftnj9n0zj9azf8vuqes6d5lsymw3fm这是我的账号，
![(}IH22 ~E2W$LR7ZZ~_Q4@T](https://github.com/unisat-wallet/extension/assets/116423401/2c9a1af0-4fa9-44e0-aa17-120e56cec4f1)
图片显示转了，但是链上还不显示，我选择当时的gas说是30分钟现在一天了，吃不上饭了，链上都查不到

**Comment by Y12310** [comment]
链上都查不到

**Comment by cloud6605** [comment]
请问现在问题解决了么？

**Comment by cloud6605** [comment]
你的地址下没有未确认的交易。既然你的问题已经解决了，我就关掉这个ticket了。
