### ISSUE TITLE
Is it possible to do a batch sendInscription?

### ISSUE THREAD

**Issue by steebchen** [unisat-wallet/extension#52]
I am trying to send some inscriptions to muliple recipients (addresses), however it seems I can only do one by one, and I have to confirm each with the unisat extension:

```
window.unisat.sendInscription("...", "<id")
```

Is it possible to either 1) auto-approve these transactions somehow, or 2) is there a method available to batch send multiple inscriptions at once? Similar to how you can make transferable inscriptions on unisat.io with a single signature (even though it creates multiple btc transactions).

Any input is appreciated!

**Comment by cloud6605** [comment]
Currently, batch sending of inscriptions is not supported. When sending in bulk, users may not pay attention to which specific inscriptions are being sent, which can lead to some fraudulent situations.

**Comment by steebchen** [comment]
Makes sense, thanks for your comment. I'm wondering if there is any way around it for developers, it's fine if it only works in some dev mode or something, or with a completely separate tool
