### ISSUE TITLE
在mint （VMPX)代币时候使用平台第一中支付方式，币安由于网路延时，导致很长时间没有到账，平台没有给mint代币（VMPX)后，BTC已转到平台，请返还

### ISSUE THREAD

**Issue by wangq588** [unisat-wallet/extension#55]
https://user-images.githubusercontent.com/103318685/237061711-3ff4e6e3-87d7-47f2-963b-3154dc01f33e.png

**Comment by wangq588** [comment]
转账证明
我币安钱包地址：1Pc81i7x8NtP4wNddAuNPb9ipb8Lg59x7U

**Comment by cloud6605** [comment]
你好，请问你有在discord时开ticket么？如果问题仍然没有解决，麻烦发一下你接收铭文的地址或者订单号，我们会核实一下，然后处理退款问题。

**Comment by cloud6605** [comment]
发现你已在别的目录提过相同的问题，那这个ticket我就关了哈。
