### ISSUE TITLE
恢复钱包显示不了旧钱包的地址

### ISSUE THREAD

**Issue by zhouben654321** [unisat-wallet/extension#57]
用助记词恢复了Unisat钱包生成不了旧地址，全部都新地址，我的钱包地址bc1pysrtvrgptcg5mvqcynkndmkcntfy29ghp44068cfw33avsn28mwqme9y3x

**Comment by cloud6605** [comment]
看看其他地址类型下面有没有。可以点设置，再点address type去看看taproot地址上有没有。
如果仍然没有，在当前taproot地址类型下新建一个地址，看看是否有以前的地址。

**Comment by cloud6605** [comment]
另外你在新建钱包时，是否要有设置派生路径，加密短语，如果有，在恢复时也得输入才行。
