### ISSUE TITLE
我的钱包里面有0.0131个btc，为什么只能用0.001个，赶紧跟我解决一下。

### ISSUE THREAD

**Issue by xwyyfc** [unisat-wallet/extension#60]
![image](https://github.com/unisat-wallet/extension/assets/38022709/a5cc1259-9465-46b1-91ac-57d37299d108)
：bc1ql2jnlu27cmp8rgxkxdhshh9q23m6jy7e6pt47x

**Comment by cloud6605** [comment]
Your balance includes the inscriptions sats. And make sure there's no unconfirmed tx.
