### ISSUE TITLE
Test signPsbt transfer needs to support 44

### ISSUE THREAD

**Issue by keepresolve** [unisat-wallet/extension#62]
https://github.com/unisat-wallet/extension/blob/master/src/background/controller/wallet.ts  number:386 

 if ((keyring.addressType === AddressType.P2TR || keyring.addressType === AddressType.M44_P2TR) && !v.tapInternalKey) {
            v.tapInternalKey = toXOnly(Buffer.from(account.pubkey, 'hex'));
}

I don't know if it is correct, if there is a bug, please fix.

**Comment by cloud6605** [comment]
Yes, it's a bug. We've fixed it in v1.1.25. thanks for your feedback.
