### ISSUE TITLE
连接钱包问题

### ISSUE THREAD

**Issue by pujianguo** [unisat-wallet/extension#65]
页面停留一段时间后钱包后台断开了，然后调用所有钱包方法都无效，也不会报错，刷新页面就好了，用什么方法能判断钱包未连接呢

**Comment by cxss** [comment]
I reported the same issue but the project owner has no comment about it. See https://github.com/unisat-wallet/extension/issues/54  and https://github.com/unisat-wallet/extension/issues/9

**Comment by cloud6605** [comment]
Sorry for my delay. Now, the locked time of latest version is 30 minutes. It is only five minutest in previous version.
