### ISSUE TITLE
Add vauld decryptor to extract privkey or procedure to mannually add a wallet into unisats

### ISSUE THREAD

**Issue by rvie17** [unisat-wallet/extension#66]
Would like to have some help from the dev team of the wallet long story short I lost my wallet lost the seed and got it back using bytes by bytes recovery I have the data salt and IV but I don't find any way of putting it easily back into unisats. I have tried a thousand way to fit it in the .log wallet file but didn't manage to ... Can you add one of the requested please

**Comment by cloud6605** [comment]
Thanks for your sugestion. I've written down it, maybe we'll consider it in future version.
