### ISSUE TITLE
钱包无法正常使用了

### ISSUE THREAD

**Issue by chengzi0919** [unisat-wallet/extension#67]
5.21铭刻图片一直没有确认，导致现在钱包正常功能无法使用。
地址是：bc1pfxfvmqrcm9q8jswjx5p7xh7nq92x7glrtw0urcv7gdpluyr5ks7sm52cyk
orderId: 128e868a34c96552240987c4b84c714c961f1ff6

![微信图片_20230527095335](https://github.com/unisat-wallet/extension/assets/134752435/d39807b3-78f9-48b6-9944-4ee13750ba8c)
![微信图片_20230527095342](https://github.com/unisat-wallet/extension/assets/134752435/53734b86-eebd-4c7b-9c4d-e3ced1153500)

**Comment by cloud6605** [comment]
订单0eafa1ab197d2cfd41436d67d0aee3ad4bacc45b已退款，txid: 4b5f82c46a83f409381f3b60af84305bcae1b847fb5b2f483ff6169f18474cab
查收地址：bc1pfxfvmqrcm9q8jswjx5p7xh7nq92x7glrtw0urcv7gdpluyr5ks7sm52cyk
