### ISSUE TITLE
助记词导出bug

### ISSUE THREAD

**Issue by xpcrack** [unisat-wallet/extension#68]
![7a2eb274d76a0246ae90a3828b21721](https://github.com/unisat-wallet/extension/assets/32606909/5157cda2-e056-4623-af9b-cb6304a53ae9)
在这个界面下，白勾勾选了2号钱包，然后点击1号钱包右边的齿轮键选择导出助记词，这个时候导出的助记词依然是2号的助记词；因为这个bug我在备份钱包的时候误认为下面几个钱包都是同一套助记词，于是在只存了一套助记词的情况下重装了钱包插件，然后发现只能恢复一个钱包。希望项目方能够补偿因为这个bug导致的我的损失。

**Comment by cloud6605** [comment]
非常感谢你的反馈。
但其实在创建钱包时就需要你备份助记词的，那个时候就可以知道，一个钱包一套助记词。钱包这么重要的东西，我们要养成良好的备份习惯，也要有谨慎的态度。
虽然我们的钱包有bug,但是不影响你备份正确的助记词。你的财产损失非平台的问题。抱歉，我们无法补偿。
