### ISSUE TITLE
computer crashed saved seed, but unable to access btc address.

### ISSUE THREAD

**Issue by ChuckRivers** [unisat-wallet/extension#69]
Hi, I had generated 2 addresses on unisat wallet,  and the wallet extension was deleted.  When installed and using recover seed.  The wallet created holding the btc is unable to be accessed?  Please any help much appreciated in advance.

**Comment by cloud6605** [comment]
Do you mean after re-installing, you can't find the original address? Please describe it in detail, then we can help you.

**Comment by cloud6605** [comment]
OK, now I understand you. Is the address holding btc in account 1 or 2?
When creating your wallet, did you set the HDpath or Phrase ?
![image](https://github.com/unisat-wallet/extension/assets/132422140/79e79112-9c40-4f4b-85e4-a77d8ab3b447)

**Comment by GGG888GGG** [comment]
@ChuckRivers Do you need more help?

**Comment by ChuckRivers** [comment]
the address is holding a few inscriptions in account #2.
Yes, I have the seed phrase
 But retrieving the address with the seed phrase only takes me to wallet
account #1, and I cannot find wallet account #2.   How can we retrieve it?
Thankyou

**Comment by cloud6605** [comment]
just click account dropdown list, then click the + button to add account 2, then your account will be resotred.
![image](https://github.com/unisat-wallet/extension/assets/132422140/99d1a235-1965-4214-ac47-a15ebd5b5ffa)
![image](https://github.com/unisat-wallet/extension/assets/132422140/c14efbf8-c0d9-49fd-9a33-e552644fc9fb)

**Comment by GGG888GGG** [comment]
@ChuckRivers

**Comment by ChuckRivers** [comment]
Thank you for the reply and advise.  I tried adding up to #10 accounts and
not any of them have the correct address with the inscriptions.    Is there
a way to see which address has the inscriptions and bitcoin?

I appreciate the help.
Regards....

**Comment by GGG888GGG** [comment]
try to close and re-open the browser to get the new version of unisat and then re-try. According to your description, it could restore your account 1, then it should also restore account 2 with same seeds, if not, it seems you may remember by mistake, the address you want to restore was other wallet with other seeds. @ChuckRivers
