### ISSUE TITLE
Feature Request: Allow Sending Bitcoin to Multiple Addresses in a Single Transaction

### ISSUE THREAD

**Issue by Brunvelop** [unisat-wallet/extension#7]
I'd like to suggest a new feature that I believe would improve the wallet's functionality and provide an added level of convenience to users. Currently, the wallet only supports sending Bitcoin to a single address per transaction. In some scenarios, users may need to send Bitcoin to multiple recipients simultaneously. This can be achieved by allowing multiple outputs in a single transaction.

Here's a brief overview of the proposed feature:

Enhance the "Send" functionality by allowing users to add multiple recipient addresses and corresponding amounts.
Implement a user interface that enables users to add, remove, and edit recipient addresses and amounts easily.
Ensure that the total amount of Bitcoin being sent in a single transaction does not exceed the wallet's available balance.
Adjust the transaction fee calculation to accommodate multiple outputs.
This feature would not only save users time and effort but also minimize transaction fees and reduce the overall congestion on the Bitcoin network. In addition, it aligns with the standard practice followed by many other popular wallets in the market.

I hope you consider implementing this feature in the near future, as it would make the wallet even more versatile and user-friendly. Thank you for your attention, and I look forward to any feedback you may have.

**Comment by cloud6605** [comment]
Thanks for your suggestion. I"ve written it down, maybe we'll consider it in future version.
