### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by swissremo** [unisat-wallet/extension#72]
Hey guys i can't check my unisats wallet. it says unvalid token IDOCTYPE. i hope it's not a scam. i participated in some WL projects for btc nfts. would be amazing if you guys could check it. if it's a scamy token you can also trade away.

Kind regards,
remo

**Comment by uroboroi** [comment]
have the same issue since today (just recognized) but last time I bought/inscribed something was yesterday. I don´t think it´s a scam. seems more an coding issue

**Comment by cloud6605** [comment]
> Hey guys i can't check my unisats wallet. it says unvalid token IDOCTYPE. i hope it's not a scam. i participated in some WL projects for btc nfts. would be amazing if you guys could check it. if it's a scamy token you can also trade away.
> 
> Kind regards, remo

Give my your wallet address, or the inscription number of  IDOCTYPE, I'll check it.

**Comment by cloud6605** [comment]
> 

Maybe you got front run. Tell me the order id, I'll check it.
