### ISSUE TITLE
just put a brc-20  but get this error : Unexpected token '<' , "<!DOCTYPE "... is not valid JSON 

### ISSUE THREAD

**Issue by Arobs598** [unisat-wallet/extension#73]

**Comment by uroboroi** [comment]
have the same issue since today (just recognized) but last time I bought/inscribed something was yesterday

**Comment by Arobs598** [comment]
I read something saying unisat is down, but not sure.

**Comment by PicklErik21** [comment]
seems more people are experiencing this issue and their website seems to have an issue as well, so I expect it to be down?!

**Comment by cloud6605** [comment]
Yes.
