### ISSUE TITLE
same value for confirmed and unconfirmed?

### ISSUE THREAD

**Issue by web3luhao** [unisat-wallet/extension#74]
https://github.com/unisat-wallet/extension/blob/bbbf0c367e004cbd674a9ec47f4929a9deb314b1/src/background/controller/provider/controller.ts#L100

**Comment by cloud6605** [comment]
Yes, it's a bug. We'll fix it in the next version.

**Comment by MTR1400** [comment]
Thank you very much dearly ❤️🙏🎉💯

در تاریخ دوشنبه ۱۲ ژوئن ۲۰۲۳،‏ ۱۰:۴۳ ق.ظ cloud6605 ***@***.***>
نوشت:

**Comment by cloud6605** [comment]
It's already fixed. Please update your wallet.
