### ISSUE TITLE
Sign psbt without finalizing inputs

### ISSUE THREAD

**Issue by timechainz** [unisat-wallet/extension#77]
Hello,

Is it possible to request a psbt signature via signPsbt() but not have the inputs finalized?  Finalizing the inputs makes it much more difficult to validate the signature independently.  This is important in a decentralized order book workflow so that buy/sell offers could be validated upfront.  In this use case, the signed PSBT is intended to be combined with other inputs before finalization and thus should not be prematurely finalized.  In bitcoin-cli the walletprocesspsbt tool has a "finalize" parameter for this purpose.  Could something similar be added to unisat?

Here's an example of a sell offer on openordex for inscription #0 with an invalid finalized input.

https://openordex.org/inscription?number=6fb976ab49dcec017f1e201e84395983204ae1a7c2abf7ced0a85d692e442799i0#sellerSignedPsbt=cHNidP8BAFICAAAAAe1h73A6zedruNERV6JU7Ty1IlYZh2KO1cBklZqCMEy8AAAAAAD/////ARAnAAAAAAAAFgAUS0GlfqWSeEWIpwPwrvRIjBbJQroAAAAAAAEA/TgBAQAAAAABAnGJ6st1FIvYLEVbJMQaZ3HSOJnkw5C+ViCuJYiFEYosAAAAAAD9////xuZd0xArNSaBuElLX3nzjwtZW95O7L/wbz94v+v0vuYAAAAAAP3///8CECcAAAAAAAAiUSAVbMSHgwYVdyBgfNy0syr6TMaFOGhFjXJYuQcRLlpDS8hgBwAAAAAAIlEgthWGz3o2R7WpgjIK52ODoEaA/0HcImSUjVk6agZgghwBQIP9WWErMfeBBYyuHuSZS7MdXVICtlFgNveDrvuXeQGSZl1gGG6/r3Aw7h9TifGtoA+7JwYBjLMcEG6hbeyQGXIBQNSqKH1p/NFzO9bxe9vpvBZQIaX5Qa9SY2NfNCgSRNabmX5EiaihWcLC+ALgchm7DUfYrAmi1r4uSI/YaQ1lq8gAAAAAAQErECcAAAAAAAAiUSAVbMSHgwYVdyBgfNy0syr6TMaFOGhFjXJYuQcRLlpDSwEDBIMAAAABCEMBQZUpv6e1Hwfpi/PpglkkK/Rx40vZIIHwtJ7dXWFZ5TcZUEelCnfKOAWZ4xWjauYM2y+JcgFcVsuPzPuiM+z5AH+DARNBlSm/p7UfB+mL8+mCWSQr9HHjS9kggfC0nt1dYVnlNxlQR6UKd8o4BZnjFaNq5gzbL4lyAVxWy4/M+6Iz7PkAf4MBFyC6ZCT2zZVrEbkw/T1fyS8eLKQaP2MH6rzdlMauGvQzLQAA

Thanks!

**Comment by huanniangstudio** [comment]
Please refer this
unisat.signPsbt(psbtHex[, options])
```
try {
  let res = await window.unisat.signPsbt("70736274ff01007d....",{autoFinalized:false});
  console.log(res)
} catch (e) {
  console.log(e);
}
```

**Comment by timechainz** [comment]
Ahh, perfect.  I didn't realize that was an option.  Thanks!

**Comment by tanzile789** [comment]
unisat.signPsbt(psbtHex[, options])
May I ask how pabtHex obtained it

**Comment by GGG888GGG** [comment]
@tanzile789 about api question, please send your request to [contact@unisat.io](mailto:contact@unisat.io)
