### ISSUE TITLE
Permission to use brc20-api-v2 endpoints

### ISSUE THREAD

**Issue by geoffsmiths** [unisat-wallet/extension#80]
Hi, I was unable to reach you through discord or twitter.

Currently I am in the progress of creating an app that uses the brc20-api-v2 data which unisat.io is also using. 

Am I free to use the data or do I need permission for that?

Many thanks in advance!

All the best

**Comment by cloud6605** [comment]
You may open ticket in discord support-ticket channel. Our team will help you there.
About the api, yes, it's free to use at present. May you introduce your project, and tell me why do you want to use it.
