### ISSUE TITLE
wallet must have at least one account

### ISSUE THREAD

**Issue by patrick99e99** [unisat-wallet/extension#81]
When I click connect I get:

<img width="663" alt="Screen Shot 2023-06-13 at 11 15 32 PM" src="https://github.com/unisat-wallet/extension/assets/28946/1bf84f50-fb85-4205-8afd-fa1a89582c11">

This has happened in both Chrome and Brave Browser.

**Comment by cloud6605** [comment]
Do you already have unisat wallet?
Please click "Click here to refresh the page" to try again.

**Comment by patrick99e99** [comment]
I did click that and it does nothing.

I believe this problem happens after uninstalling the unisat browser extension after creating a wallet, and reinstalling the extension and trying to create a new wallet.

The only way I could get around this was to quit Brave and go into my /Library/Application Support folder and remove the Brave Browser folder so that it would reinitialize everything.

**Comment by cloud6605** [comment]
That's weird. Thanks for your feedback and glad that you finally figure it out. We'll do more test and try to improve our wallet.

**Comment by ebjj123** [comment]
I have the same error message with no idea how to correct it. I'm using a Chrome browser in my MAC OS. Any help would be appreciated.

**Comment by GGG888GGG** [comment]
@ebjj123 please try to clear the cache in browser and close/reopen the browser, try again. Hope for good news.
