### ISSUE TITLE
 ORDI is invalid

### ISSUE THREAD

**Issue by Even521** [unisat-wallet/extension#83]
ORDI is invalid，inscription_number : 361640

https://ordinals.com/inscription/28ce5b6a8bf5cf4800127d4394a4fb69e633bc9491220ad07f43d634820d007ai0

**Comment by cloud6605** [comment]
I'm sorry, it was spent as fee.
![image](https://github.com/unisat-wallet/extension/assets/132422140/bf7ba577-be47-4644-85dd-654941d815a8)

**Comment by Even521** [comment]
![image](https://github.com/unisat-wallet/extension/assets/9923368/5cdf795c-375c-458e-8508-b3a445cd9087)
https://unisat.io/brc20?t=1688024734260&q=bc1qe594y2hzlhqgksefxslluza2mm2nz02hpe7vp5  
The mint of 361640 was not found，minter is bc1qe594y2hzlhqgksefxslluza2mm2nz02hpe7vp5

**Comment by Even521** [comment]
> I'm sorry, it was spent as fee. ![image](https://user-images.githubusercontent.com/132422140/249025475-bf7ba577-be47-4644-85dd-654941d815a8.png)

![image](https://github.com/unisat-wallet/extension/assets/9923368/a53a94c6-0b27-40ef-98d2-34d239b7e513)
https://unisat.io/brc20?t=1688024734260&q=bc1qe594y2hzlhqgksefxslluza2mm2nz02hpe7vp5
The mint of 361640 was not found，minter is bc1qe594y2hzlhqgksefxslluza2mm2nz02hpe7vp5

**Comment by cloud6605** [comment]
Yes, that inscriptions was spent as fee. From the tx (dd13b2f3f8e3423ef1a66e4bdee2c7bb53f113fd86da20c80f1d6ed0ae924f56), you used other wallet to transfer your BTC, and that wallet didn't recognize it as an ordinal, so it was sent as normal btc.

**Comment by Even521** [comment]
> Yes, that inscriptions was spent as fee. From the tx (dd13b2f3f8e3423ef1a66e4bdee2c7bb53f113fd86da20c80f1d6ed0ae924f56), you used other wallet to transfer your BTC, and that wallet didn't recognize it as an ordinal, so it was sent as normal btc.

Thanks, I see, but still following the BRC-20 protocol, for which this should be valid BRC-20MINT. There is only one hint in the document as shown below
![image](https://github.com/unisat-wallet/extension/assets/9923368/7fcd9ece-043f-4f94-b7fb-f4480b05b593)

**Comment by cloud6605** [comment]
Our dev has checked the inscription 361640. And found it is invalid, because the content length is 72 bytes, but not 71 bytes, it has two more "00" in the end. And its content is a Hexadecimal file, but not a readable file.
You may check it on https://ordinals.com/inscription/28ce5b6a8bf5cf4800127d4394a4fb69e633bc9491220ad07f43d634820d007ai0 by yourself.
![image](https://github.com/unisat-wallet/extension/assets/132422140/59d00d50-ecfa-4d1e-9303-9e406ecf0276)

**Comment by GGG888GGG** [comment]
@Even521
