### ISSUE TITLE
Unable to publish fully signed PSBT

### ISSUE THREAD

**Issue by ankit-flnc** [unisat-wallet/extension#85]
# Description
- have created a PSBT for transferring inscription
- inscription in in unisat wallet and both seller and buyer have signed the PSBT via unisat wallet (chrome extension)
- when tried to publish the fully signed PSBT via unisat.pushPsbt() function, im getting below error

```
code: 
-32603
data: 
originalError: 
message: 
"dust"
stack: 
"Error: dust\n    at T.<anonymous> (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:130931)\n    at f (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1552586)\n    at Generator.<anonymous> (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1552344)\n    at Generator.next (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1552941)\n    at u (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1545181)\n    at i (chrome-extension://ppbibelpcjmhbdihakflkdcoccbgbkpo/background.js:1:1545378)"
```

i have checked the PSBT and all of the output are above dust limti, ideally i shouldnot be getting this error.

PS: also tried to publish the tx via mempool.space/tx/push, but getting error "TX decode failed. Make sure the tx has at least one input."

**Comment by GGG888GGG** [comment]
@ankit-flnc Please kindly help provide PSBT to check.
