### ISSUE TITLE
Unable to recover unisat 

### ISSUE THREAD

**Issue by Asad1976** [unisat-wallet/extension#89]
Hi 
I unable to recover my unisat wallet from same computer. I just delete the chrome extension and reinstall the same. Can you please help me in this regard.
Thanks.

**Comment by GGG888GGG** [comment]
you need to use the same mnemonic words, address type(derivative path), phrase(optional, if you set when created) when restore, then you could restore the same address, and also did you create multiple accounts under this wallet? if so, you also need to create the same amount accounts under it. @Asad1976

**Comment by Asad1976** [comment]
thanks. im still facing the same trouble. The wallet is not recongnizing the mnemonic phrase and doesnt let me getting into my wallet. The phrase is same. Can you let me know the solution of this. Even my activity on this wallet can be checked which is happening from the last few months. Please help me in this regard. Thanks.

**Comment by GGG888GGG** [comment]
the solution I gave to you in my last reply. Please try to remember all the information when created carefully, if you still can not restore the same address, I'm afraid we also have no way to help you more.

1. the same mnemonic words.
2. set the same address type
3. If you set a different derivative path when created, fill in the same derivative path.
4. if you set phrase when created, fill it.
5. If you created multiple accounts under this wallet, for example, what you want to restore is the fourth one, after your restore the first account, you need to mannually create the next three accounts under this wallet. You could find the address in fourth.

**Comment by GGG888GGG** [comment]
![create multi accounts](https://github.com/unisat-wallet/extension/assets/132530469/a4393415-eba6-46fe-8f6e-e4cdadd52c51)

**Comment by GGG888GGG** [comment]
![restore wallet address](https://github.com/unisat-wallet/extension/assets/132530469/2a9551c6-18c9-4389-a578-d0175365e321)

**Comment by GGG888GGG** [comment]
@Asad1976

**Comment by GGG888GGG** [comment]
How about this issue? We just release a new version 1.1.25. Please close and re-open the browser, then try the latest version of unisat to re-restore the wallet, it will scan the first ten accounts and list the account which has the assets. Hope for good news. 
@Asad1976

**Comment by GGG888GGG** [comment]
@Asad1976 any update on this?
