### ISSUE TITLE
Unable to call methods such as signMessage or requestAccount after leaving the page for a long time and returning.

### ISSUE THREAD

**Issue by gitwujiaolong** [unisat-wallet/extension#9]
Unable to call methods such as signMessage or requestAccount after leaving the page for a long time and returning.

**Comment by cxss** [comment]
Yes, I have the same issue.  It only can be resolved by refreshing page but which will cause user state loss.

**Comment by cloud6605** [comment]
The latest version has solved this issue. Please update your wallet.
