### ISSUE TITLE
.sats marketplace

### ISSUE THREAD

**Issue by vsium** [unisat-wallet/extension#91]
I have listed some .sats and 15 minutes it was unlisted just like that. And now io can't list them back in. Am i missing something and it's a bug?

**Comment by GGG888GGG** [comment]
please, the wallet address and inscription number. @vsium

**Comment by vsium** [comment]
bc1qzd4ej7knpm8xkzvtmfyty8nzcc7tkqzkzefkfj

[#14839072](http://ordinals.com/inscription/30baee9dcf20f650be85852f6a90b5d32e97a2426eb1b52cb5d0fe8beaebcf39i0)
[#14839074](http://ordinals.com/inscription/7f6a6cf4350bad619eadfedb436948974df2bb08c6a76b10d80d92fcc04f1371i0)
[#14839075](http://ordinals.com/inscription/8424728e894951609386567d2e11ab1ddb5ef60d1b78c0186a4441a8dab6308bi0)
[#14839069](http://ordinals.com/inscription/6ec0f3d2c66cdd9f453098cc9ecb01df803efc160f9bf6d59bb879c78a77e0bdi0)
[#14839076](http://ordinals.com/inscription/400acc154dc7c90284781f9dd01e0cbba76f3fadbb1f414fb0eb3c9355598298i0)
[#14839077](http://ordinals.com/inscription/7d8fe3467394defa8290c8cedd88aea2f193e6474244d1a86c8de4b6a5ffc8c0i0)
[#14839071](http://ordinals.com/inscription/ac29e5bfa83c56aff9e75f8b48978c67da4c47f8122e9dceabdb52d3903cff57i0)
[#14839070](http://ordinals.com/inscription/c372652b0465096c186dfc5e34efb3e0f3c21a0649ac53fe52ff8ed92a155ac1i0)
[#14839073](http://ordinals.com/inscription/28e7b92f4361f4c50cbfec48f5fc128ef199aad70a446c2eb44fb58801c0b46fi0)

Thanks

**Comment by GGG888GGG** [comment]
by checking on the mempool, you sent multiple inscriptions to other address, you could check this tx https://mempool.space/tx/0ad936d31bb57087bc079583cc2ea39a7dcbab6b597f4566adca862eb21b5b0c , it seems you may send them to exchange, right? You could remember why you made this tx? And what wallet did you use to operate this tx?

And through multiple transferring, 
14839072,14839075,14839071 are still in your address zkzefkfj. You may re-list them ad tell us if you could or not, if not, we will help you more. You could check the records of 14839071 on this web https://ordiscan.com/inscription/14839071  (fill in the inscription number to search the records.)

14839069,14839070,14839077 are in the address 
bc1p0dn05vtsn8afs8prqvjej84zhmutpafm9pm0qhteepc5nvlguuws9ll4mh.

14839073 is in the address 3G81qkHjHWxRhErr46pwoX5ApHw1bpGckX.

And 14839074 and 14839076 were spent as fee in the above tx. @vsium

**Comment by vsium** [comment]
wooow what a mess, my brain that is...i will have to check all this...i was using too much wallet..now using only unisat but i did not put it all on another market 15 minutes after putting it on unisat. I remember visiting ordswap and other market but i dont remember listing anything on it. Really weird i will take the time to evaluate what i did and get back to you.

Thanks

**Comment by vsium** [comment]
something went terribly wrong for me..and i dont get it!

bc1p0dn05vtsn8afs8prqvjej84zhmutpafm9pm0qhteepc5nvlguuws9ll4mh is not me
3G81qkHjHWxRhErr46pwoX5ApHw1bpGckX is not me

I have been using unisat for the inscription i did lots of .sats and around 70 bitmap and now lost some .sats and most of the bitmap.

And how can i spend .sats as fee???

I inscribe most of the .sats with lookordinals and i will follow up with them... but something happen when i listed with you. I remember doing something on MagicEden also.

I am very very confused on how can this happen. 

Soem of the bitmap went from there bc1p0dn05vtsn8afs8prqvjej84zhmutpafm9pm0qhteepc5nvlguuws9ll4mh to there bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj and none are mine.

Do you guys have a genius with some tools that can figure it out? thanks

**Comment by vsium** [comment]
is this one of your adress https://magiceden.io/ordinals/wallet?walletAddress=bc1qxhmdufsvnuaaaer4ynz88fspdsxq2h9e9cetdj

lots of my bitmap that was inscribe on unisat is now there from bc1p0dn05vtsn8afs8prqvjej84zhmutpafm9pm0qhteepc5nvlguuws9ll4mh not mine and my adress bc1qzd4ej7knpm8xkzvtmfyty8nzcc7tkqzkzefkfj

**Comment by vsium** [comment]
i talked a lot with the discord of rarity garden and because i was using the fucking shitty sparrow wallet i inscribe some .sats and send out most of my bitmap and other .sats as payment which is the main fucking stupid stuff i ever did using shittysparrow. And now i understand why you said spent as fee for two of the .sats that was listed. I thought listing a inscription on your site or any other site it would lock the inscription which would make sense in the old ways to do basic stuff. But now shitty btc chain nooo. you spent the utxo inscribed as fee. 

But only with sparrow they told me. But i would like to know how did you know the two above And 14839074 and 14839076 were spent as fee in the above tx. @vsium ?

BEcause i would like to know which other one i spent as fees? around 50 bitmap and a lots of .sats ?

If possible please let me know how you knew that?

Thanks

**Comment by GGG888GGG** [comment]
Using unisat to do the operations, Unisat doesn't allow to use inscriptions as gas fee, but if you imported the wallet to other wallet tool, we can not control what you do.

And the place I already told you in my last reply,  "https://ordiscan.com/inscription/14839071 (fill in the inscription number to search the records.)" It is https://ordiscan.com/.

https://ordiscan.com/inscription/14839074
https://ordiscan.com/inscription/14839076

**Comment by vsium** [comment]
yeah thanks i used trac to list all that is left of everything.....what a mess...i spent 80% of my inscription as fee...horrible

thanks
