### ISSUE TITLE
Testnet issue

### ISSUE THREAD

**Issue by 0xcielo** [unisat-wallet/extension#97]
Refused to load the script '/content/...i0' because it violates the following Content Security Policy directive: "script-src 'none'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

This is the html
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><script xlink:href="/content/...i0"></script></svg>

I am using testet. is it normal?

**Comment by 0xcielo** [comment]
Blockheight does not exists on testnet

**Comment by GGG888GGG** [comment]
@0xcielo is it ok now? If not, could you please provide us inscription ID?

**Comment by GGG888GGG** [comment]
@0xcielo it should be fixed. Please try again. If still any problem, please tell us the details and also provide us inscription ID.

**Comment by huanniangstudio** [comment]
Fixed
